# Generated by Django 3.2 on 2023-02-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0002_lock_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='is_locked',
        ),
    ]
