# Generated by Django 3.2 on 2023-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0003_remove_lock_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
