# Generated by Django 3.2 on 2022-11-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kurikulum', '0004_auto_20221110_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran_awal', models.IntegerField()),
                ('tahun_ajaran_akhir', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id_neosia', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('tipe_semester', models.PositiveSmallIntegerField(choices=[('1', 'Ganjil'), ('2', 'Genap')])),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kurikulum')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.tahunajaran')),
            ],
        ),
    ]
