# Generated by Django 3.2 on 2022-11-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0004_auto_20221110_2137'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='kurikulum',
        ),
        migrations.CreateModel(
            name='SemesterKurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kurikulum')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
            ],
        ),
    ]
