# Generated by Django 3.2 on 2022-12-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0003_alter_semester_tipe_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tahunajaran',
            options={'ordering': ('tahun_ajaran_awal', 'tahun_ajaran_akhir')},
        ),
    ]
