# Generated by Django 3.2 on 2022-12-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_programstudi_fakultas'),
        ('semester', '0004_alter_tahunajaran_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaranProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programstudi')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterProdi',
            fields=[
                ('id_neosia', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
                ('tahun_ajaran_prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.tahunajaranprodi')),
            ],
        ),
    ]
