# Generated by Django 3.2 on 2022-12-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_area', '0005_auto_20221230_1803'),
        ('semester', '0005_semesterprodi_tahunajaranprodi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SemesterKurikulum',
        ),
    ]
