# Generated by Django 3.2 on 2023-01-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_programstudijenjang_options'),
        ('semester', '0006_delete_semesterkurikulum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunajaranprodi',
            name='prodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programstudijenjang'),
        ),
    ]
