# Generated by Django 3.2 on 2023-01-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0007_alter_tahunajaranprodi_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tahunajaranprodi',
            old_name='prodi',
            new_name='prodi_jenjang',
        ),
    ]
