# Generated by Django 3.2 on 2022-12-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semester', '0004_alter_tahunajaran_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semesterkurikulum')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndicatorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_code', models.CharField(max_length=20)),
                ('assessment_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_area.assessmentarea')),
            ],
        ),
    ]
