# Generated by Django 3.2 on 2022-12-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentarea',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
            preserve_default=False,
        ),
    ]
