# Generated by Django 3.2 on 2022-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_area', '0002_assessmentarea_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentarea',
            name='color',
            field=models.CharField(choices=[('Default', 'badge-custom-gray'), ('Merah', 'badge-custom-red'), ('Orange', 'badge-custom-orange'), ('Kuning', 'badge-custom-yellow'), ('Hijau', 'badge-custom-green'), ('Biru', 'badge-custom-blue'), ('Ungu', 'badge-custom-purple')], default='Default', max_length=7),
        ),
    ]
