# Generated by Django 3.2 on 2022-12-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0005_delete_matakuliahkurikulum'),
        ('pi_area', '0004_auto_20221221_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentarea',
            name='semester',
        ),
        migrations.AddField(
            model_name='assessmentarea',
            name='kurikulum',
            field=models.ForeignKey(default=864, on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kurikulum'),
            preserve_default=False,
        ),
    ]
