# Generated by Django 3.2 on 2023-02-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0004_lock_is_locked'),
        ('pi_area', '0005_auto_20221230_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentarea',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
        migrations.AddField(
            model_name='performanceindicator',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
        migrations.AddField(
            model_name='performanceindicatorarea',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
    ]
