# Generated by Django 3.2 on 2022-12-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah', '0002_auto_20221223_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenmatakuliah',
            name='mk_semester',
        ),
        migrations.RemoveField(
            model_name='pesertamatakuliah',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='pesertamatakuliah',
            name='mk_semester',
        ),
        migrations.CreateModel(
            name='KelasMataKuliahSemester',
            fields=[
                ('id_neosia', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=255)),
                ('mk_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah.matakuliahsemester')),
            ],
        ),
        migrations.AddField(
            model_name='dosenmatakuliah',
            name='kelas_mk_semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah.kelasmatakuliahsemester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesertamatakuliah',
            name='kelas_mk_semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah.kelasmatakuliahsemester'),
            preserve_default=False,
        ),
    ]
