# Generated by Django 3.2 on 2022-12-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0005_semesterprodi_tahunajaranprodi'),
        ('mata_kuliah', '0003_auto_20221227_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahsemester',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semesterprodi'),
        ),
    ]
