# Generated by Django 3.2 on 2023-01-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah', '0004_alter_matakuliahsemester_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliahkurikulum',
            name='kurikulum',
        ),
        migrations.RemoveField(
            model_name='matakuliahkurikulum',
            name='prodi',
        ),
    ]
