# Generated by Django 3.2 on 2023-01-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_programstudijenjang_options'),
        ('mata_kuliah_kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahkurikulum',
            name='prodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programstudijenjang'),
        ),
    ]
