# Generated by Django 3.2 on 2023-01-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_kurikulum', '0002_alter_matakuliahkurikulum_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='prodi',
            new_name='prodi_jenjang',
        ),
    ]
