# Generated by Django 3.2 on 2023-01-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_kurikulum', '0003_rename_prodi_matakuliahkurikulum_prodi_jenjang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliahkurikulum',
            name='prodi_jenjang',
        ),
    ]
