# Generated by Django 3.2 on 2023-03-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_kurikulum', '0005_auto_20230329_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahkurikulum',
            old_name='praktek_sks',
            new_name='praktik_sks',
        ),
    ]
