# Generated by Django 3.2 on 2023-04-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_kurikulum', '0006_rename_praktek_sks_matakuliahkurikulum_praktik_sks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliahkurikulum',
            name='praktik_sks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matakuliahkurikulum',
            name='teori_sks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
