# Generated by Django 3.2 on 2022-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
