# Generated by Django 3.2 on 2022-10-25 14:26

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221025_2207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', accounts.managers.UserOAuthManager()),
            ],
        ),
    ]
