# Generated by Django 3.2 on 2022-10-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221028_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='password',
        ),
    ]
