# Generated by Django 3.2 on 2022-12-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221125_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='fakultas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.fakultas'),
        ),
    ]
