# Generated by Django 3.2 on 2023-01-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230107_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudijenjang',
            name='total_sks_lulus',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
