# Generated by Django 3.2 on 2023-01-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_programstudijenjang_total_sks_lulus'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudijenjang',
            name='nama',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
