# Generated by Django 3.2 on 2023-01-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_programstudijenjang_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudijenjang',
            name='total_sks_lulus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
