# Generated by Django 3.2 on 2023-01-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_programstudijenjang_total_sks_lulus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programstudijenjang',
            options={'ordering': ['jenjang_studi__id_neosia']},
        ),
    ]
