# Generated by Django 3.2 on 2023-01-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_programstudijenjang_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='nama',
        ),
    ]
