# Generated by Django 3.2 on 2023-02-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0002_lock_is_locked'),
        ('clo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lock_model.lock'),
        ),
        migrations.AddField(
            model_name='komponenclo',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lock_model.lock'),
        ),
    ]
