# Generated by Django 3.2 on 2023-02-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0004_lock_is_locked'),
        ('clo', '0002_auto_20230217_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
        migrations.AlterField(
            model_name='komponenclo',
            name='lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
    ]
