# Generated by Django 3.2 on 2023-02-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock_model', '0004_lock_is_locked'),
        ('clo', '0004_auto_20230218_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='piclo',
            name='lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock'),
        ),
    ]
