# Generated by Django 3.2 on 2023-03-01 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0019_pesertamatakuliah_status_nilai'),
        ('clo', '0007_auto_20230224_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiCloPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo.clo')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.pesertamatakuliah')),
            ],
            options={
                'ordering': ['clo__nama'],
            },
        ),
        migrations.AddConstraint(
            model_name='nilaiclopeserta',
            constraint=models.CheckConstraint(check=models.Q(('nilai__gte', 0.0), ('nilai__lte', 100.0)), name='nilai_clo_peserta_range'),
        ),
    ]
