# Generated by Django 3.2 on 2023-03-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clo', '0008_auto_20230301_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clo',
            options={},
        ),
    ]
