# Generated by Django 3.2 on 2023-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clo', '0009_alter_clo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenclo',
            name='teknik_penilaian',
            field=models.CharField(choices=[('observasi', 'Observasi'), ('partisipasi', 'Partisipasi'), ('unjuk kerja', 'Unjuk kerja'), ('tes tertulis', 'Tes tertulis'), ('tes lisan', 'Tes lisan'), ('angket', 'Angket')], max_length=255),
        ),
    ]
