# Generated by Django 3.2 on 2022-12-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0004_alter_tahunajaran_options'),
        ('ilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilo',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='semester.semesterkurikulum'),
            preserve_default=False,
        ),
    ]
