# Generated by Django 3.2 on 2022-12-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pi_area', '0003_alter_assessmentarea_color'),
        ('ilo', '0003_auto_20221208_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilo',
            name='pi_area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pi_area.performanceindicatorarea'),
        ),
    ]
