# Generated by Django 3.2 on 2022-12-23 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilo', '0004_alter_ilo_pi_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilo',
            name='persentase_capaian_ilo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='ilo',
            name='satisfactory_level',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddConstraint(
            model_name='ilo',
            constraint=models.CheckConstraint(check=models.Q(('satisfactory_level__gte', 0.0), ('satisfactory_level__lte', 100.0)), name='satisfactory_level_range'),
        ),
    ]
