# Generated by Django 3.2 on 2023-04-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilo', '0005_auto_20221223_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilo',
            name='persentase_capaian_ilo',
        ),
    ]
