# Generated by Django 3.2 on 2023-04-01 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilo', '0006_remove_ilo_persentase_capaian_ilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilo',
            name='persentase_capaian_ilo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
