# Generated by Django 3.2 on 2023-01-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0006_auto_20230102_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelasmatakuliahsemester',
            name='kelas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
