# Generated by Django 3.2 on 2023-01-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0007_alter_kelasmatakuliahsemester_kelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosenmatakuliah',
            old_name='mahasiswa',
            new_name='dosen',
        ),
    ]
