# Generated by Django 3.2 on 2023-01-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0008_rename_mahasiswa_dosenmatakuliah_dosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimatakuliahmahasiswa',
            name='peserta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.pesertamatakuliah'),
        ),
    ]
