# Generated by Django 3.2 on 2023-01-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0009_alter_nilaimatakuliahmahasiswa_peserta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelasmatakuliahsemester',
            name='kelas',
        ),
    ]
