# Generated by Django 3.2 on 2023-01-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0011_alter_kelasmatakuliahsemester_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenmatakuliah',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pesertamatakuliah',
            name='id',
        ),
        migrations.AddField(
            model_name='dosenmatakuliah',
            name='id_neosia',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nilaimatakuliahmahasiswa',
            name='nilai_huruf',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='pesertamatakuliah',
            name='id_neosia',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
