# Generated by Django 3.2 on 2023-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0012_auto_20230119_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenmatakuliah',
            name='id_neosia',
        ),
        migrations.AddField(
            model_name='dosenmatakuliah',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
