# Generated by Django 3.2 on 2023-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0014_auto_20230124_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliahsemester',
            name='is_clo_locked',
            field=models.BooleanField(default=False),
        ),
    ]
