# Generated by Django 3.2 on 2023-02-22 08:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0016_matakuliahsemester_is_rps_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageCloAchievementMataKuliahSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('mk_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.matakuliahsemester')),
            ],
        ),
        migrations.AddConstraint(
            model_name='averagecloachievementmatakuliahsemester',
            constraint=models.CheckConstraint(check=models.Q(('nilai__gte', 0.0), ('nilai__lte', 100.0)), name='nilai_mk_semester_range'),
        ),
    ]
