# Generated by Django 3.2 on 2023-02-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0017_auto_20230222_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AverageCloAchievementMataKuliahSemester',
        ),
    ]
