# Generated by Django 3.2 on 2023-03-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0020_auto_20230301_2236'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pesertamatakuliah',
            name='average_clo_achievement_peserta_range',
        ),
        migrations.RemoveField(
            model_name='pesertamatakuliah',
            name='average_clo_achievement',
        ),
    ]
