# Generated by Django 3.2 on 2023-03-02 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0021_auto_20230301_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilaimatakuliahilomahasiswa',
            options={'ordering': ['ilo__nama']},
        ),
        migrations.AlterField(
            model_name='nilaimatakuliahilomahasiswa',
            name='nilai_ilo',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
