# Generated by Django 3.2 on 2023-04-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0024_nilaiexcelmatakuliahsemester_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliahsemester',
            old_name='is_rps_locked',
            new_name='is_rencanapembelajaransemester_locked',
        ),
    ]
