# Generated by Django 3.2 on 2022-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurikulum',
            name='tahun_akhir',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kurikulum',
            name='tahun_mulai',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
