# Generated by Django 3.2 on 2022-11-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_myuser_password'),
        ('kurikulum', '0003_auto_20221031_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurikulum',
            name='tahun_akhir',
        ),
        migrations.AlterField(
            model_name='kurikulum',
            name='total_sks_lulus',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MataKuliahKurikulum',
            fields=[
                ('id_neosia', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('kode', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=255)),
                ('sks', models.PositiveSmallIntegerField()),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.kurikulum')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programstudi')),
            ],
        ),
    ]
