# Generated by Django 3.2 on 2022-11-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0004_auto_20221110_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MataKuliahKurikulum',
        ),
    ]
