# Generated by Django 3.2 on 2023-01-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0005_delete_matakuliahkurikulum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurikulum',
            name='total_sks_lulus',
        ),
    ]
