# Generated by Django 3.2 on 2023-01-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_programstudijenjang_options'),
        ('kurikulum', '0006_remove_kurikulum_total_sks_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurikulum',
            name='prodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.programstudijenjang'),
        ),
    ]
