# Generated by Django 3.2 on 2023-01-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0007_alter_kurikulum_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurikulum',
            old_name='prodi',
            new_name='prodi_jenjang',
        ),
    ]
