# Generated by Django 3.2 on 2023-02-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0008_rename_prodi_kurikulum_prodi_jenjang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurikulum',
            name='is_assessmentarea_locked',
            field=models.BooleanField(default=False),
        ),
    ]
