# Generated by Django 3.2 on 2023-03-23 07:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clo', '0009_alter_clo_options'),
        ('mata_kuliah_semester', '0024_nilaiexcelmatakuliahsemester_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaPembelajaranSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('deskripsi', models.TextField()),
                ('clo_details', models.TextField()),
                ('materi_pembelajaran', models.TextField()),
                ('pustaka_utama', models.TextField(blank=True, null=True)),
                ('pustaka_pendukung', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('kaprodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mk_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.matakuliahsemester')),
            ],
        ),
        migrations.CreateModel(
            name='PertemuanRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertemuan_awal', models.PositiveSmallIntegerField()),
                ('pertemuan_akhir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('learning_outcome', models.TextField()),
                ('indikator', models.TextField()),
                ('bentuk_kriteria', models.TextField()),
                ('materi_pembelajaran', models.TextField()),
                ('bobot_penilaian', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo.clo')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rencanapembelajaransemester')),
            ],
        ),
        migrations.CreateModel(
            name='PengembangRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rencanapembelajaransemester')),
            ],
        ),
        migrations.CreateModel(
            name='PembelajaranPertemuanRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pertemuan', models.CharField(choices=[('on', 'Online'), ('off', 'Offline')], max_length=3)),
                ('bentuk_pembelajaran', models.TextField()),
                ('metode_pembelajaran', models.TextField()),
                ('pertemuan_rps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rps.pertemuanrps')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliahSyaratRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.matakuliahsemester')),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rencanapembelajaransemester')),
            ],
        ),
        migrations.CreateModel(
            name='KoordinatorRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rencanapembelajaransemester')),
            ],
        ),
        migrations.CreateModel(
            name='DurasiPertemuanRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pertemuan', models.CharField(choices=[('on', 'Online'), ('off', 'Offline')], max_length=3)),
                ('tipe_durasi', models.CharField(max_length=255)),
                ('pengali_durasi', models.SmallIntegerField()),
                ('durasi_menit', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('pertemuan_rps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rps.pertemuanrps')),
            ],
        ),
        migrations.CreateModel(
            name='DosenPengampuRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rencanapembelajaransemester')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pertemuanrps',
            constraint=models.CheckConstraint(check=models.Q(('bobot_penilaian__gte', 0.0), ('bobot_penilaian__lte', 100.0)), name='bobot_penilaian_pertemuan_rps_range'),
        ),
        migrations.AddConstraint(
            model_name='durasipertemuanrps',
            constraint=models.CheckConstraint(check=models.Q(('durasi_menit__gte', 0.0), ('durasi_menit__lte', 60.0)), name='durasi_menit_pertemuan_rps_range'),
        ),
    ]
