# Generated by Django 3.2 on 2023-03-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durasipertemuanrps',
            name='tipe_durasi',
            field=models.CharField(max_length=100),
        ),
    ]
