# Generated by Django 3.2 on 2023-03-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mata_kuliah_semester', '0024_nilaiexcelmatakuliahsemester_created_at'),
        ('rps', '0002_alter_durasipertemuanrps_tipe_durasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanapembelajaransemester',
            name='mk_semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.matakuliahsemester'),
        ),
    ]
