# Generated by Django 3.2 on 2023-03-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0004_alter_pertemuanrps_rps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pertemuanrps',
            old_name='rps',
            new_name='mk_semester',
        ),
    ]
