# Generated by Django 3.2 on 2023-03-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0005_rename_rps_pertemuanrps_mk_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertemuanrps',
            name='bentuk_kriteria',
        ),
        migrations.RemoveField(
            model_name='pertemuanrps',
            name='indikator',
        ),
        migrations.RemoveField(
            model_name='pertemuanrps',
            name='learning_outcome',
        ),
        migrations.RemoveField(
            model_name='pertemuanrps',
            name='materi_pembelajaran',
        ),
        migrations.AddField(
            model_name='pertemuanrps',
            name='tipe_pertemuan',
            field=models.CharField(choices=[('reg', 'Reguler'), ('tes', 'Ujian Mid/Final')], default='reg', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RincianPertemuanRPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_outcome', models.TextField()),
                ('materi_pembelajaran', models.TextField()),
                ('indikator', models.TextField()),
                ('bentuk_kriteria', models.TextField()),
                ('pertemuan_rps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rps.pertemuanrps')),
            ],
        ),
    ]
