# Generated by Django 3.2 on 2023-03-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0006_auto_20230330_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durasipertemuanrps',
            name='pertemuan_rps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.pertemuanrps'),
        ),
        migrations.AlterField(
            model_name='pembelajaranpertemuanrps',
            name='pertemuan_rps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.pertemuanrps'),
        ),
    ]
