# Generated by Django 3.2 on 2023-03-31 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0007_auto_20230330_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertemuanrps',
            name='bobot_penilaian',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='pertemuanrps',
            name='tipe_pertemuan',
            field=models.CharField(choices=[('reg', 'Reguler'), ('mid', 'Ujian Mid'), ('fin', 'Ujian Final')], max_length=3),
        ),
    ]
