# Generated by Django 3.2 on 2023-04-17 09:02

from django.db import migrations, models
import django.db.models.deletion
import rps.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mata_kuliah_semester', '0025_rename_is_rps_locked_matakuliahsemester_is_rencanapembelajaransemester_locked'),
        ('lock_model', '0004_lock_is_locked'),
        ('rps', '0010_auto_20230415_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencanaPembelajaranSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_rps', models.FileField(upload_to=rps.utils.rps_upload_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lock_model.lock')),
                ('mk_semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mata_kuliah_semester.matakuliahsemester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
