# Generated by Django 3.2 on 2023-04-17 09:48

from django.db import migrations, models
import learning_outcomes_assessment.validators
import rps.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0011_rencanapembelajaransemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rencanapembelajaransemester',
            name='file_rps',
            field=models.FileField(upload_to=rps.utils.rps_upload_handler, validators=[learning_outcomes_assessment.validators.validate_pdf_file]),
        ),
    ]
